id: P000031
initial_creation_type: ebook
created_at: 31/01/2020
last_modified_at: 25/11/2021
source_metadata:
  title: ༄༅། །བླ་མའི་ཐུགས་སྒྲུབ་བར་ཆད་ཀུན་སེལ་ལས། ཞལ་གདམས་སྙིང་བྱང་གི་འགྲེལ་བཤད་སྙིང་པོར་དྲིལ་བ་རྩ་གསུམ་སྒྱུ་འཕྲུལ་དྲྭ་བའི་རོལ་རྩེད་ཅེས་བྱ་བ་བཞུགས་སོ།
    །
  authors:
  - མཛད་པ་པོ། ༧སྐྱབས་རྗེ་དིལ་མགོ་མཁྱེན་བཙེ་རིན་པོ་ཆེ།
  layers:
  - book_title
  - author
  - sabche
  id: SHE-DKR-16
web_metadata:
  title:
    en: The Creative Play of the Illusory Net of the Three Roots:A Commentary on the
      Section on Quintessential Advice from the Dispeller of All Obstacles, the Heart
      Accomplishment of the Guru
    bo: བླ་མའི་ཐུགས་སྒྲུབ་བར་ཆད་ཀུན་སེལ་ལས།ཞལ་གདམས་སྙིང་བྱང་གི་འགྲེལ་བཤད་སྙིང་པོར་དྲིལ་བ་རྩ་གསུམ་སྒྱུ་འཕྲུལ་དྲྭ་བའི་རོལ་རྩེད་ཅེས་བྱ་བ་བཞུགས་སོ།
  collection:
    en: ''
    bo: དིལ་མགོ་མཁྱེན་བཙེ་གསུང་འབུམ།–  དེབ། ༡༦
  author:
    en: Kyabje Dilgo Khyentse Rinpoche
    bo: ༧སྐྱབས་རྗེ་དིལ་མགོ་མཁྱེན་བཙེ་རིན་པོ་ཆེ།
  pusblisher:
    en: Shechen Publications
    bo: ཞེ་ཆེན་བསྟན་གཉིས་དར་རྒྱས་གླིང།
  sku: SHE-DKR-16
  category:
    en: Uncategorized
    bo: Uncategorized @tib
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: SHE-DKR-16.epub
  description:
    en: ''
    bo: ''
